### ISSUE TITLE
Out of Service Appearing incorrectly

### ISSUE THREAD

**Issue by lramos15** [rpiambulance/slack-integrations#4]
When we're put out of service the /whoson command shows Crew chief, driver, and attendants all as out of service. Instead of just showing a singular line that says Out of Service

**Comment by ddbruce** [comment]
This should be fixed in [this commit](https://github.com/rpiambulance/website/commit/fe6795921efbfda3b5eeef6c32d3eaa0972b82bd), over on the website repo.
